//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TC_CoilOperation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Inverted_Value_X {
            get {
                return ((double)(this["Inverted_Value_X"]));
            }
            set {
                this["Inverted_Value_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20000")]
        public double Inverted_Value_Y {
            get {
                return ((double)(this["Inverted_Value_Y"]));
            }
            set {
                this["Inverted_Value_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8000")]
        public double Inverted_Value_Z {
            get {
                return ((double)(this["Inverted_Value_Z"]));
            }
            set {
                this["Inverted_Value_Z"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-3200")]
        public double Offset_Value_X {
            get {
                return ((double)(this["Offset_Value_X"]));
            }
            set {
                this["Offset_Value_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Offset_Value_Y {
            get {
                return ((double)(this["Offset_Value_Y"]));
            }
            set {
                this["Offset_Value_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Offset_Value_Z {
            get {
                return ((double)(this["Offset_Value_Z"]));
            }
            set {
                this["Offset_Value_Z"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Lifter_Signal_Interval {
            get {
                return ((int)(this["Lifter_Signal_Interval"]));
            }
            set {
                this["Lifter_Signal_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Lifter_Signal_ON_Judgment {
            get {
                return ((int)(this["Lifter_Signal_ON_Judgment"]));
            }
            set {
                this["Lifter_Signal_ON_Judgment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Lifter_Signal_OFF_Judgment {
            get {
                return ((int)(this["Lifter_Signal_OFF_Judgment"]));
            }
            set {
                this["Lifter_Signal_OFF_Judgment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Lifter_Manualmode {
            get {
                return ((bool)(this["Lifter_Manualmode"]));
            }
            set {
                this["Lifter_Manualmode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string BackNum {
            get {
                return ((string)(this["BackNum"]));
            }
            set {
                this["BackNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COIL")]
        public string Oracle_UserID {
            get {
                return ((string)(this["Oracle_UserID"]));
            }
            set {
                this["Oracle_UserID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COIL")]
        public string Oracle_UserPass {
            get {
                return ((string)(this["Oracle_UserPass"]));
            }
            set {
                this["Oracle_UserPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COIL")]
        public string Oracle_ServiceName {
            get {
                return ((string)(this["Oracle_ServiceName"]));
            }
            set {
                this["Oracle_ServiceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int Add_day {
            get {
                return ((int)(this["Add_day"]));
            }
            set {
                this["Add_day"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM22")]
        public string xport_name {
            get {
                return ((string)(this["xport_name"]));
            }
            set {
                this["xport_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com23")]
        public string yport_name {
            get {
                return ((string)(this["yport_name"]));
            }
            set {
                this["yport_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com24")]
        public string zport_name {
            get {
                return ((string)(this["zport_name"]));
            }
            set {
                this["zport_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int xbaudrate {
            get {
                return ((int)(this["xbaudrate"]));
            }
            set {
                this["xbaudrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int ybaudrate {
            get {
                return ((int)(this["ybaudrate"]));
            }
            set {
                this["ybaudrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int zbaudrate {
            get {
                return ((int)(this["zbaudrate"]));
            }
            set {
                this["zbaudrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int xdatabit {
            get {
                return ((int)(this["xdatabit"]));
            }
            set {
                this["xdatabit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int ydatabit {
            get {
                return ((int)(this["ydatabit"]));
            }
            set {
                this["ydatabit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int zdatabit {
            get {
                return ((int)(this["zdatabit"]));
            }
            set {
                this["zdatabit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DIO000000")]
        public string Lifter_DIOid {
            get {
                return ((string)(this["Lifter_DIOid"]));
            }
            set {
                this["Lifter_DIOid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public string antena_decibel {
            get {
                return ((string)(this["antena_decibel"]));
            }
            set {
                this["antena_decibel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string antena_stoptime {
            get {
                return ((string)(this["antena_stoptime"]));
            }
            set {
                this["antena_stoptime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string XcomIP {
            get {
                return ((string)(this["XcomIP"]));
            }
            set {
                this["XcomIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string ZcomIP {
            get {
                return ((string)(this["ZcomIP"]));
            }
            set {
                this["ZcomIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string DIOcomIP {
            get {
                return ((string)(this["DIOcomIP"]));
            }
            set {
                this["DIOcomIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\20001\\\\Desktop\\\\coilsound\\\\警告音1.mp3")]
        public string MP3_1 {
            get {
                return ((string)(this["MP3_1"]));
            }
            set {
                this["MP3_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\20001\\\\Desktop\\\\coilsound\\\\警告音2.mp3")]
        public string MP3_2 {
            get {
                return ((string)(this["MP3_2"]));
            }
            set {
                this["MP3_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B2")]
        public string YardID {
            get {
                return ((string)(this["YardID"]));
            }
            set {
                this["YardID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string YcomIP {
            get {
                return ((string)(this["YcomIP"]));
            }
            set {
                this["YcomIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0665-7477-4100")]
        public string tagID {
            get {
                return ((string)(this["tagID"]));
            }
            set {
                this["tagID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("169.254.200.100")]
        public string RFIDcomIP {
            get {
                return ((string)(this["RFIDcomIP"]));
            }
            set {
                this["RFIDcomIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int XTimeout {
            get {
                return ((int)(this["XTimeout"]));
            }
            set {
                this["XTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int YTimeout {
            get {
                return ((int)(this["YTimeout"]));
            }
            set {
                this["YTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int ZTimeout {
            get {
                return ((int)(this["ZTimeout"]));
            }
            set {
                this["ZTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Windows\\System32\\shutdown.exe")]
        public string Shutdownpass {
            get {
                return ((string)(this["Shutdownpass"]));
            }
            set {
                this["Shutdownpass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("160")]
        public string antena_decibel_A {
            get {
                return ((string)(this["antena_decibel_A"]));
            }
            set {
                this["antena_decibel_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("170")]
        public string antena_decibel_B {
            get {
                return ((string)(this["antena_decibel_B"]));
            }
            set {
                this["antena_decibel_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public string antena_decibel_C {
            get {
                return ((string)(this["antena_decibel_C"]));
            }
            set {
                this["antena_decibel_C"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("190")]
        public string antena_decibel_D {
            get {
                return ((string)(this["antena_decibel_D"]));
            }
            set {
                this["antena_decibel_D"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public string antena_decibel_E {
            get {
                return ((string)(this["antena_decibel_E"]));
            }
            set {
                this["antena_decibel_E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int X_sikiti {
            get {
                return ((int)(this["X_sikiti"]));
            }
            set {
                this["X_sikiti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Y_sikiti {
            get {
                return ((int)(this["Y_sikiti"]));
            }
            set {
                this["Y_sikiti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Z_sikiti {
            get {
                return ((int)(this["Z_sikiti"]));
            }
            set {
                this["Z_sikiti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string IDYARD {
            get {
                return ((string)(this["IDYARD"]));
            }
            set {
                this["IDYARD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36")]
        public string Free_X {
            get {
                return ((string)(this["Free_X"]));
            }
            set {
                this["Free_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Free_manual_mode {
            get {
                return ((bool)(this["Free_manual_mode"]));
            }
            set {
                this["Free_manual_mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int 重複Y調整値 {
            get {
                return ((int)(this["重複Y調整値"]));
            }
            set {
                this["重複Y調整値"] = value;
            }
        }
    }
}
